//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_SHopping_Cart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class BaseCategory_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseCategory_Table()
        {
            this.ProductCategory_Table = new HashSet<ProductCategory_Table>();
        }

        public int BaseCatId { get; set; }
        [Remote("IsBaseCategoryNameExist", "Admin",
             ErrorMessage = "Base Category name already exists")]
        [Required]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Use alphabets and spaces only please.")]
        public string BaseCatName { get; set; }
        [Required]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Use alphabets and spaces only please.")]
        public string BaseCatDesc { get; set; }
        public string BaseCatCreatedBy { get; set; }
        public System.DateTime BaseCatCreateDate { get; set; }
        public string BaseCatUpdatedBy { get; set; }
        public System.DateTime BaseCatUpdateDate { get; set; }
        public bool BaseCatIsDeleted
        {
            get; set;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory_Table> ProductCategory_Table { get; set; }
    }
}
