//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_SHopping_Cart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_Table
    {
        public int ImageId { get; set; }
        public int Productid { get; set; }
        public byte[] BinaryImage { get; set; }
        public string ImageCreatedBy { get; set; }
        public System.DateTime ImageCreatedDate { get; set; }
        public string ImageUpdatedBy { get; set; }
        public System.DateTime ImageUpdatedDate { get; set; }
        public bool ImageIsDeleted { get; set; }
    
        public virtual Product_Table Product_Table { get; set; }
    }
}
