//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_SHopping_Cart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoppingCartDbEntities : DbContext
    {
        public ShoppingCartDbEntities()
            : base("name=ShoppingCartDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaseCategory_Table> BaseCategory_Table { get; set; }
        public virtual DbSet<Image_Table> Image_Table { get; set; }
        public virtual DbSet<Location_Table> Location_Table { get; set; }
        public virtual DbSet<Notify_table> Notify_table { get; set; }
        public virtual DbSet<Order_Table> Order_Table { get; set; }
        public virtual DbSet<OrderDetail_Table> OrderDetail_Table { get; set; }
        public virtual DbSet<Product_Table> Product_Table { get; set; }
        public virtual DbSet<ProductCategory_Table> ProductCategory_Table { get; set; }
        public virtual DbSet<Role_Table> Role_Table { get; set; }
        public virtual DbSet<Service_Table> Service_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
