//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_SHopping_Cart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify_table
    {
        public int Notifyid { get; set; }
        public int Userid { get; set; }
        public int Productid { get; set; }
        public int flag { get; set; }
    
        public virtual Product_Table Product_Table { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
