//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_SHopping_Cart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_Table()
        {
            this.OrderDetail_Table = new HashSet<OrderDetail_Table>();
        }
    
        public int ServiceId { get; set; }
        public int Productid { get; set; }
        public int Locationid { get; set; }
        public int ServiceProviderid { get; set; }
        public string ServiceName { get; set; }
        public decimal DeliveryCharge { get; set; }
        public string ServiceDesc { get; set; }
        public string ServiceCreatedBy { get; set; }
        public System.DateTime ServiceCreatedDate { get; set; }
        public string ServiceUpdatedBy { get; set; }
        public System.DateTime ServiceUpdatedDate { get; set; }
        public bool ServiceIsDeleted { get; set; }
    
        public virtual Location_Table Location_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail_Table> OrderDetail_Table { get; set; }
        public virtual Product_Table Product_Table { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
